substitutions:
  device_name: esp32cam02
  device_platform: esp32
  device_board: esp32cam
  # device_ip: 192.168.1.178
  # device_gw: 192.168.1.1
  # device_mask: 255.255.255.0

<<: !include common/base.yaml


esp32_camera:
  name: micamara02
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  max_framerate: 12fps
  resolution: 640x480
  jpeg_quality: 10
  vertical_flip: false
  horizontal_mirror: true
  special_effect: none

# Servidor de vídeo
esp32_camera_web_server:
  - port: 80
    mode: stream
  - port: 8088
    mode: snapshot
