substitutions:
  device_name: garagecam
  device_platform: esp32
  device_board: esp32cam
  device_interval: 300s
  device_temp_offset: "0.6"

<<: !include common/base.yaml

i2c:
  sda: GPIO14
  scl: GPIO15
  scan: True
  id: bus_a

esp32_camera:
  name: micamara1
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  max_framerate: 20fps
  resolution: 640x480
  jpeg_quality: 10
  vertical_flip: false
  horizontal_mirror: False
  special_effect: none
  id: cam1

# Servidor de vídeo
esp32_camera_web_server:
  - port: 80
    mode: stream
  - port: 8088
    mode: snapshot

# RESTART ESP
button:
  - platform: restart
    name: "Restart button"
    id: restart_button

sensor:
  - platform: bmp280
    temperature:
      name: "Temperatura"
      oversampling: 16x
      filters:
        - multiply: $device_temp_offset
    pressure:
      name: "Presion"
    address: 0x76
    update_interval: $device_interval
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: $device_interval
  # - platform: hdc1080
  #   temperature:
  #     name: "Temperatura"
  #     id: tempsensor
  #     filters:
  #       - sliding_window_moving_average:
  #           window_size: 5
  #           send_every: 1
  #   humidity:
  #     name: "Humedad"
  #     id: humiditysensor
  #     filters:
  #       - sliding_window_moving_average:
  #           window_size: 5
  #           send_every: 1
  #   update_interval: 60s
  # - platform: ultrasonic
  #   trigger_pin: GPIO12
  #   echo_pin: GPIO13
  #   name: "Distance"
  #   unit_of_measurement: cm
  #   update_interval: 60s
  #   filters:
  #     - lambda: return (x * 100);

binary_sensor:
  - platform: gpio
    pin: GPIO13
    name: "PIR"
    id: sr505
    filters:
      - delayed_off: 30s

mqtt:
  broker: !secret mqtt_broker
  discovery_prefix: !secret mqtt_prefijo
  username: !secret mqtt_username
  password: !secret mqtt_password
  on_message:
    - topic: $device_name/button/restart
      payload: "RESTART"
      then:
        - button.press: restart_button
