substitutions:
  device_name: esphomedht22mqtt
  device_platform: esp8266
  device_board: d1_mini


  
<<: !include common/base.yaml

# RESTART ESP
button:
  - platform: restart
    name: "Restart button"
    id: restart_button




mqtt:
  broker: !secret mqtt_broker
  discovery_prefix: !secret mqtt_prefijo
  username: !secret mqtt_username
  password: !secret mqtt_password
  on_message:
    - topic: $device_name/button/restart
      payload: "RESTART"
      then:
        - button.press: restart_button

