substitutions:
  device_name: espcampir
  device_platform: esp32
  device_board: esp32cam

<<: !include common/base.yaml

# i2c:
#   sda: GPIO14
#   scl: GPIO15
#   # scan: True
#   # id: bus_a

esp32_camera:
  name: micamara
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  max_framerate: 12fps
  resolution: 640x480
  jpeg_quality: 10
  vertical_flip: false
  horizontal_mirror: true
  special_effect: none
  id: cam1

# Servidor de vídeo
esp32_camera_web_server:
  - port: 80
    mode: stream
  - port: 8088
    mode: snapshot
# i2c:
#   sda: GPIO14
#   scl: GPIO15
#   # scan: True
#   # id: bus_a

# sensor:
#   - platform: hdc1080
#     temperature:
#       name: "Temperatura"
#       id: tempsensor
#       filters:
#         - sliding_window_moving_average:
#             window_size: 5
#             send_every: 1
#     humidity:
#       name: "Humedad"
#       id: humiditysensor
#       filters:
#         - sliding_window_moving_average:
#             window_size: 5
#             send_every: 1
#     update_interval: 60s
#   # - platform: ultrasonic
#   #   trigger_pin: GPIO12
#   #   echo_pin: GPIO13
#   #   name: "Distance"
#   #   unit_of_measurement: cm
#   #   update_interval: 60s
#   #   filters:
#   #     - lambda: return (x * 100);

binary_sensor:
  - platform: gpio
    pin: GPIO13
    name: "PIR"
    id: sr505
    # on_press:
    #   then:

mqtt:
  broker: !secret mqtt_broker
  discovery_prefix: !secret mqtt_prefijo
  #   username: !secret mqtt_username
  #   password: !secret mqtt_password
