esphome:
  name: $device_name
  platform: $device_platform
  board: $device_board
  # build_path: ./build/$device_name

  # Solo para loti.yaml ######
  on_boot:
    priority: 600
    then:
      - servo.write:
          id: my_servo
          level: -100.0%
  ##############
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  output_power: 8.5
  fast_connect: true

  # manual_ip:
  #   static_ip: $device_ip
  #   gateway: $device_gw
  #   subnet: $device_mask

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $device_name
    password: !secret wifi_ap_password

# captive_portal:

# logger:
#   level: INFO
#   logs:
#     mqtt.component: INFO
#     mqtt.client: INFO
#     esp32_camera: INFO

logger:
  level: VERBOSE
  logs:
    mqtt.component: DEBUG
    mqtt.client: DEBUG
    esp32_camera: ERROR

ota:
  password: !secret ota_password
# binary_sensor:
#   - platform: status
#     name: "$device_name status"

# NTP
time:
  - platform: sntp
    id: sntp_time
